#############################################################################
# Makefile for building: plugandpaint
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  plugandpaint.pro
# Template: subdirs
# Command: C:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile plugandpaint.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-app \
		sub-plugins-basictools \
		sub-plugins-extrafilters


sub-app-qmake_all: sub-plugins-basictools-qmake_all sub-plugins-extrafilters-qmake_all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: sub-plugins-basictools \
		sub-plugins-extrafilters FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-app-make_first: sub-plugins-basictools-make_first sub-plugins-extrafilters-make_first FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-app-all: sub-plugins-basictools-all sub-plugins-extrafilters-all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-app-clean: sub-plugins-basictools-clean sub-plugins-extrafilters-clean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-distclean: sub-plugins-basictools-distclean sub-plugins-extrafilters-distclean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets: sub-plugins-basictools-install_subtargets sub-plugins-extrafilters-install_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets: sub-plugins-basictools-uninstall_subtargets sub-plugins-extrafilters-uninstall_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-plugins-basictools-qmake_all:  FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	cd plugins\basictools\ && $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && $(MAKE) -f Makefile qmake_all
sub-plugins-basictools: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-plugins-basictools-make_first: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-plugins-basictools-all: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-plugins-basictools-clean: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-plugins-basictools-distclean: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-plugins-basictools-install_subtargets: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-plugins-basictools-uninstall_subtargets: FORCE
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-plugins-extrafilters-qmake_all:  FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	cd plugins\extrafilters\ && $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && $(MAKE) -f Makefile qmake_all
sub-plugins-extrafilters: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile
sub-plugins-extrafilters-make_first: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile 
sub-plugins-extrafilters-all: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile all
sub-plugins-extrafilters-clean: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile clean
sub-plugins-extrafilters-distclean: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile distclean
sub-plugins-extrafilters-install_subtargets: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile install
sub-plugins-extrafilters-uninstall_subtargets: FORCE
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: plugandpaint.pro C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qml_debug.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\declarative_debug.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf \
		plugandpaint.pro
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile plugandpaint.pro
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\qml_debug.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\declarative_debug.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf:
C:\Qt\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf:
plugandpaint.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile plugandpaint.pro

qmake_all: sub-app-qmake_all sub-plugins-basictools-qmake_all sub-plugins-extrafilters-qmake_all FORCE

make_first: sub-app-make_first sub-plugins-basictools-make_first sub-plugins-extrafilters-make_first  FORCE
all: sub-app-all sub-plugins-basictools-all sub-plugins-extrafilters-all  FORCE
clean: sub-app-clean sub-plugins-basictools-clean sub-plugins-extrafilters-clean  FORCE
distclean: sub-app-distclean sub-plugins-basictools-distclean sub-plugins-extrafilters-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-app-install_subtargets sub-plugins-basictools-install_subtargets sub-plugins-extrafilters-install_subtargets FORCE
uninstall_subtargets: sub-app-uninstall_subtargets sub-plugins-basictools-uninstall_subtargets sub-plugins-extrafilters-uninstall_subtargets FORCE

sub-app-debug: sub-plugins-basictools-debug sub-plugins-extrafilters-debug
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-plugins-basictools-debug:
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
sub-plugins-extrafilters-debug:
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-app-debug sub-plugins-basictools-debug sub-plugins-extrafilters-debug

sub-app-release: sub-plugins-basictools-release sub-plugins-extrafilters-release
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-plugins-basictools-release:
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
sub-plugins-extrafilters-release:
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile release
release: sub-app-release sub-plugins-basictools-release sub-plugins-extrafilters-release

sub-app-check: sub-plugins-basictools-check sub-plugins-extrafilters-check
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\app\app.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-plugins-basictools-check:
	@if not exist plugins\basictools\ mkdir plugins\basictools\ & if not exist plugins\basictools\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\basictools\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\basictools\basictools.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
sub-plugins-extrafilters-check:
	@if not exist plugins\extrafilters\ mkdir plugins\extrafilters\ & if not exist plugins\extrafilters\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\extrafilters\ && ( if not exist Makefile $(QMAKE) C:\Users\CPU10495-local\Documents\QT_projects\plugandpaint\plugins\extrafilters\extrafilters.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=declarative_debug" "CONFIG+=qml_debug" -o Makefile ) && $(MAKE) -f Makefile check
check: sub-app-check sub-plugins-basictools-check sub-plugins-extrafilters-check
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

